apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  lebels:
    app: nginx  # deployment 的标签
spec:
  replicas: 3   # 副本数
  selector:     # 定义deployment 如何查找要管理的pod
    matchLabels:
      app: nginx   # 选择带有哪些标签的pod去控制
    matchExpressions:
      - key: app
        operator: In
        values:
          - nginx
      - key: disktype
        operator: Exists

  template:        # pod spec
    metadata:
      name: nginx  # pod 的名称
      labels:
        app: nginx # pod 的标签, 要与 selector matchLabels 匹配，否则无法控制
    spec:
      containers:
      - name: nginx
        image: nginx:1.19
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
          requests:
            memory: "64Mi"
            cpu: "250m"
        ports:
        - containerPort: 80
        volumeMounts:
        - name: share-data
          mountPath: /usr/share/nginx/html
      volumes:
      - name: share-data
        emptyDir: {}
      - name: data
        hostPath: 
          path: /data/hostpath
      - name: nfsdata
        nfs:
          server: 10.10.10.10
          path: /data/nfs
  strategy:                       # 更新策略
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1