apiVersion: v1
kind: ServiceAccount
metadata:
  name: myserviceaccount
  namespace: default
  labels:
    app: myapp
imagePullSecrets:
- name: my-image-pull-secret

---
apiVersion: v1
kind: Pod
metadata:
  name: mypod
  namespace: default
  labels:
    app: myapp
spec:
  serviceAccountName: myserviceaccount
  containers:
  - name: mycontainer
    image: nginx:latest
    ports:
    - containerPort: 80
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
      requests:
        memory: "64Mi"
        cpu: "250m"