apiVersion: v1
kind: Service
metadata:
  name: mystatefulset-headless
spec:
  clusterIP: None
  selector:
    app: myapp
  ports:
  - port: 80
    targetPort: 80
    name: web
# statefulset的服务必须是headless的
  # headless服务的特性是没有clusterIP
  # 这样可以让每个pod都有一个独立的DNS地址
  # 例如：  pod-0.mystatefulset-headless.default.svc.cluster.local
  #        pod-1.mystatefulset-headless.default.svc.cluster.local
  #        pod-2.mystatefulset-headless.default.svc.cluster.local
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mystatefulset
spec:
  selector:
    matchLabels:
      app: myapp
  serviceName: mystatefulset-headless
  replicas: 2
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      partition: 4  # 0表示不分区更新 4表示编号>=4的pod更新
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: registry.k8s.io/nginx-slim:0.8
        ports:
        - containerPort: 80
          name: web
        volumeMounts:
        - name: www
          mountPath: /usr/share/nginx/html
  # 这种写法代替了pvc的写法，动态创建pv和pvc，必须使用模板
  # 因为sts的各个pod需要与pv想对应，所以不能使用普通的volumes指令
  volumeClaimTemplates: 
  - metadata:
      name: www
    spec:
      accessModes: 
        - ReadWriteMany
      storageClassName: nfs
      resources:
        requests:
          storage: 1Gi

